version: '3.8'
services:
  app:
    build:
      context: .
      target: production
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    env_file:
      - .env
    ports:
      - '9229:9229'
      - ${APP_PORT}:${APP_PORT}
    command: npm run start
    networks:
      appnet:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./mongo/data:/data/db
    networks:
      appnet:
  redis:
    image: redis
    env_file:
      - .env
    networks:
      appnet:
networks:
  appnet:
