version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - '27017:27017'
    networks:
      appnet:
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      appnet:
networks:
  appnet:
